"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from 'next/navigation';
import { useEffect, useState } from "react";
import { Grid } from "@mui/material";
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Excercises",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [ currentExercise, setCurrentExcercise] = useState("1");
  const pathname = usePathname();

  useEffect(() => {
    document.title = "Exercises";
    const path = pathname?.split("/")[1] ? pathname?.split("/")[1] : "1";
    setCurrentExcercise(path);
}, [pathname]);

  return (
    <html lang="en">
      <body className={inter.className}>
      <Grid container sx={{ width: "100%", p: 0, m: 0 }}>
            <Grid item
                xs={1}
                sx={{height: "100vh", borderRight: "1px solid #e7e7e7"}}
            ><Sidebar currentExercise={currentExercise} />
            </Grid>
            <Grid item
                xs={11}
            >
                {children}
            </Grid>
        </Grid>
      </body>
    </html>
  );
}
